### ISSUE TITLE
[Cash-Tracker-BE] Create MongoDB provider

### ISSUE THREAD

**Issue by RafaelJuliano** [RafaelJuliano/Cash-Tracker#2]
Create a MongoDB provider to connect to DataBase.

- [x] Create a develop database named cashtracker-dev.
- [x] Save the necessary credentials into AWS Parameters Store
  - SSM credentials names:
    1 - /dev/sls/mongodb/cash-tracker
- [x] Create a resource class to build IAM permissions
- [x] Create an SSM resource class
- [x] Create a MongoDB provider
- [x] Integrate the `Hello World` lambda to get a sample value from MongoDB
