### ISSUE TITLE
[Cash-Tracker-BE] Create Accounts Payable API

### ISSUE THREAD

**Issue by RafaelJuliano** [RafaelJuliano/Cash-Tracker#3]
Create an Accounts Payable API

Model:
```js
{
  _id: ObjectId
  id: uuid
  name: string
  description?: string
  customer?: string
  originalAmount: number
  rebate?: number
  dueDate: Date
  barcode?: string
  createdAt: Date
  updatedAt: Date
  deleted: boolean
} 
```

- [ ] Create Account Payable
- [ ] Get Account Payable
- [ ] List Account Payable
- [ ] Update Account Payable
- [ ] Delete Account Payable
